language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

branches:
  only:
    - master

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - vendor/bin/coke
  - vendor/bin/atoum
