sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

branches:
  only:
    - master

before_script:
  - composer install

script:
  - vendor/bin/coke
  - vendor/bin/atoum
