language: php

php:
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=5.0.*
      
branches:
  only:
    - master

before_script:
  # disable xdebug
  - phpenv config-rm xdebug.ini
  - wget http://getcomposer.org/composer.phar
  - php composer.phar require symfony/dependency-injection:${SYMFONY_VERSION} --no-update
  - php composer.phar install

script:
  - vendor/bin/coke
  - vendor/bin/atoum
